export const PERMISSION_DEFINITIONS = [
  // users
  { module: 'users', action: 'view', description: 'View users' },
  { module: 'users', action: 'create', description: 'Create users' },
  { module: 'users', action: 'edit', description: 'Edit users' },
  { module: 'users', action: 'delete', description: 'Delete users' },
  // roles
  { module: 'roles', action: 'view', description: 'View roles & permissions' },
  { module: 'roles', action: 'manage', description: 'Create/update/delete roles' },
  // customers
  { module: 'customers', action: 'view', description: 'View customers' },
  { module: 'customers', action: 'create', description: 'Create customers' },
  { module: 'customers', action: 'edit', description: 'Edit customers' },
  { module: 'customers', action: 'delete', description: 'Delete customers' },
  { module: 'customers', action: 'export', description: 'Export customers' },
  // vehicles
  { module: 'vehicles', action: 'view', description: 'View vehicles' },
  { module: 'vehicles', action: 'create', description: 'Create vehicles' },
  { module: 'vehicles', action: 'edit', description: 'Edit vehicles' },
  { module: 'vehicles', action: 'delete', description: 'Delete vehicles' },
  { module: 'vehicles', action: 'export', description: 'Export vehicles' },
  // drivers
  { module: 'drivers', action: 'view', description: 'View drivers' },
  { module: 'drivers', action: 'create', description: 'Create drivers' },
  { module: 'drivers', action: 'edit', description: 'Edit drivers' },
  { module: 'drivers', action: 'delete', description: 'Delete drivers' },
  { module: 'drivers', action: 'assign', description: 'Assign drivers' },
  // bookings
  { module: 'bookings', action: 'view', description: 'View bookings' },
  { module: 'bookings', action: 'create', description: 'Create bookings' },
  { module: 'bookings', action: 'edit', description: 'Edit bookings' },
  { module: 'bookings', action: 'delete', description: 'Delete bookings' },
  { module: 'bookings', action: 'approve', description: 'Approve bookings' },
  { module: 'bookings', action: 'export', description: 'Export bookings' },
  // trips
  { module: 'trips', action: 'view', description: 'View trips' },
  { module: 'trips', action: 'create', description: 'Create trips' },
  { module: 'trips', action: 'edit', description: 'Edit trips' },
  { module: 'trips', action: 'assign', description: 'Assign vehicle/driver' },
  { module: 'trips', action: 'approve', description: 'Approve trip actions' },
  // fuel / maintenance / expenses
  { module: 'fuel', action: 'view', description: 'View fuel records' },
  { module: 'fuel', action: 'create', description: 'Create fuel records' },
  { module: 'fuel', action: 'edit', description: 'Edit fuel records' },
  { module: 'maintenance', action: 'view', description: 'View maintenance' },
  { module: 'maintenance', action: 'create', description: 'Create maintenance' },
  { module: 'maintenance', action: 'edit', description: 'Edit maintenance' },
  { module: 'expenses', action: 'view', description: 'View expenses' },
  { module: 'expenses', action: 'create', description: 'Create expenses' },
  { module: 'expenses', action: 'edit', description: 'Edit expenses' },
  { module: 'expenses', action: 'approve', description: 'Approve expenses' },
  // finance
  { module: 'invoices', action: 'view', description: 'View invoices' },
  { module: 'invoices', action: 'create', description: 'Create invoices' },
  { module: 'invoices', action: 'edit', description: 'Edit invoices' },
  { module: 'invoices', action: 'export', description: 'Export invoices' },
  { module: 'payments', action: 'view', description: 'View payments' },
  { module: 'payments', action: 'create', description: 'Record payments' },
  { module: 'payments', action: 'approve', description: 'Approve payments' },
  { module: 'ledger', action: 'view', description: 'View ledgers' },
  { module: 'ledger', action: 'export', description: 'Export ledgers' },
  // pod / reports / system
  { module: 'pod', action: 'view', description: 'View POD' },
  { module: 'pod', action: 'create', description: 'Upload POD' },
  { module: 'pod', action: 'approve', description: 'Verify POD' },
  { module: 'reports', action: 'view', description: 'View reports' },
  { module: 'reports', action: 'export', description: 'Export reports' },
  { module: 'notifications', action: 'view', description: 'View notifications' },
  { module: 'support', action: 'view', description: 'View support tickets' },
  { module: 'support', action: 'create', description: 'Create support tickets' },
  { module: 'support', action: 'manage', description: 'Manage support tickets' },
  { module: 'branches', action: 'view', description: 'View branches' },
  { module: 'branches', action: 'manage', description: 'Manage branches' },
  { module: 'settings', action: 'view', description: 'View settings' },
  { module: 'settings', action: 'manage', description: 'Manage settings' },
  { module: 'audit', action: 'view', description: 'View audit logs' },
  { module: 'dashboard', action: 'view', description: 'View dashboard' },
  { module: 'vendors', action: 'view', description: 'View vendors' },
  { module: 'vendors', action: 'create', description: 'Create vendors' },
  { module: 'vendors', action: 'edit', description: 'Edit vendors' },
];

const all = (modulesActions) => modulesActions;

export const ROLE_DEFINITIONS = [
  {
    name: 'Super Admin',
    slug: 'super-admin',
    description: 'Full system access',
    isSystem: true,
    // Super admin bypasses checks; still seed all permissions for UI
    permissions: 'ALL',
  },
  {
    name: 'Admin',
    slug: 'admin',
    description: 'Company administrator',
    isSystem: true,
    permissions: 'ALL',
  },
  {
    name: 'Transport Manager',
    slug: 'transport-manager',
    description: 'Fleet and operations manager',
    isSystem: true,
    permissions: [
      'dashboard:view',
      'customers:view', 'customers:create', 'customers:edit', 'customers:export',
      'vehicles:view', 'vehicles:create', 'vehicles:edit', 'vehicles:export',
      'drivers:view', 'drivers:create', 'drivers:edit', 'drivers:assign',
      'bookings:view', 'bookings:create', 'bookings:edit', 'bookings:approve', 'bookings:export',
      'trips:view', 'trips:create', 'trips:edit', 'trips:assign', 'trips:approve',
      'fuel:view', 'fuel:create', 'fuel:edit',
      'maintenance:view', 'maintenance:create', 'maintenance:edit',
      'expenses:view', 'expenses:create', 'expenses:edit', 'expenses:approve',
      'pod:view', 'pod:approve',
      'invoices:view', 'payments:view', 'ledger:view',
      'reports:view', 'reports:export',
      'notifications:view', 'support:view', 'support:manage',
      'branches:view', 'vendors:view', 'vendors:create', 'vendors:edit',
    ],
  },
  {
    name: 'Dispatcher',
    slug: 'dispatcher',
    description: 'Booking and trip dispatch',
    isSystem: true,
    permissions: [
      'dashboard:view',
      'customers:view', 'customers:create', 'customers:edit',
      'vehicles:view', 'drivers:view', 'drivers:assign',
      'bookings:view', 'bookings:create', 'bookings:edit', 'bookings:approve',
      'trips:view', 'trips:create', 'trips:edit', 'trips:assign',
      'fuel:view', 'fuel:create',
      'expenses:view', 'expenses:create',
      'pod:view',
      'reports:view',
      'notifications:view', 'support:view', 'support:create',
    ],
  },
  {
    name: 'Accountant',
    slug: 'accountant',
    description: 'Finance and settlements',
    isSystem: true,
    permissions: [
      'dashboard:view',
      'customers:view',
      'vehicles:view', 'drivers:view',
      'bookings:view', 'trips:view',
      'fuel:view', 'maintenance:view',
      'expenses:view', 'expenses:approve',
      'invoices:view', 'invoices:create', 'invoices:edit', 'invoices:export',
      'payments:view', 'payments:create', 'payments:approve',
      'ledger:view', 'ledger:export',
      'pod:view', 'pod:approve',
      'reports:view', 'reports:export',
      'notifications:view', 'support:view',
      'vendors:view', 'vendors:create', 'vendors:edit',
    ],
  },
  {
    name: 'Staff',
    slug: 'staff',
    description: 'General office staff',
    isSystem: true,
    permissions: [
      'dashboard:view',
      'users:view',
      'customers:view', 'customers:create',
      'vehicles:view', 'drivers:view',
      'bookings:view', 'bookings:create',
      'trips:view',
      'expenses:view', 'expenses:create',
      'invoices:view', 'payments:view',
      'notifications:view', 'support:view', 'support:create',
    ],
  },
  {
    name: 'Driver',
    slug: 'driver',
    description: 'Driver mobile portal',
    isSystem: true,
    permissions: [
      'dashboard:view',
      'trips:view', 'trips:edit',
      'bookings:view', 'bookings:create',
      'fuel:view', 'fuel:create',
      'expenses:view', 'expenses:create',
      'pod:view', 'pod:create',
      'notifications:view', 'support:create',
      'vehicles:view',
    ],
  },
  {
    name: 'Customer',
    slug: 'customer',
    description: 'Online customer portal',
    isSystem: true,
    permissions: [
      'dashboard:view',
      'bookings:view', 'bookings:create', 'bookings:edit',
      'trips:view',
      'pod:view',
      'invoices:view', 'payments:view', 'payments:create',
      'notifications:view', 'support:create', 'support:view',
    ],
  },
];

// silence unused helper lint if any bundler cares
void all;
